language: node_js

node_js:
  - node

addons:
  chrome: stable

before_install:
  # - wget http://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_mac64.zip
  # - unzip chromedriver_mac64.zip -d /home/travis/bin/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm start &
  - npm test

# 76.0.3809.68/chromedriver_mac64.zip
