language: node_js

node_js:
  - node

addons:
  chrome: "^74.0.0"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - sequelize db:create
  - sequelize db:migrate

script:
  - npm start &
  - npm test
